- hosts: all
  become: yes
  roles:
    - init
    - locale # for local language and time settings
    - nfs # to enable mounting project directory, dev-only
    - webserver # nginx and php
    - xdebug # to allow debugging, dev-only
    - mysql
    - composer
    - js
    - magentoInstall
    - magentoUpdate
    - phpmyadmin # to allow accessing database from browser, optional
